class CreateRooms < ActiveRecord::Migration[6.0]
  def change
    create_table :rooms do |t|
      t.string :level, default: "Autogenerated for student", null: false
      t.references :subject, null: false, foreign_key: true

      t.timestamps
    end
  end
end
